Created graph
Yu-Nakaura/OriginalApp-LA pull request #6
Opened 2022-09-24 15:57 UTC by Yu-Nakaura

グループごとの点数をゲットして棒グラフを作る機能を実装しました！
ユーザーがPersonalViewからChartViewにして、一度PersonalViewに戻して、もう一度ChartViewにしたときに勝手に数字が増えてしまうところをあと直します！これでいったんコア機能は完成です！

2022-09-26 10:06 UTC, risako070310 requested changes
LGTM✨グラフいい感じに表示できている〜〜〜レイアウトだけ修正が欲しいです><

2022-09-26 10:06 UTC, risako070310 commented on app/src/main/res/layout/fragment_login.xml
> +    tools:context=".login.LoginFragment">
パッケージ化ナイス！！pixel3での実行だとこんな感じでレイアウトが崩れているので、メールアドレスを入力するEditTextのmarginTopの数値を工夫した方がいいかも！！pixel6でのレイアウトはいい感じだった！Androidは端末ごとに画面の縦横比が違うので、marginなどの数値指定は特に注意が必要なので、固定値ではなくbiasで調整するのが良さそう👍

<img src="https://user-images.githubusercontent.com/47821463/192247463-25fb7db8-cd23-41e5-8b92-7155219fe878.png" width="300px">

2022-09-26 10:06 UTC, risako070310 commented on app/src/main/java/app/nakaura/chloe/original/todo/ToDoFragment.kt
> +    private fun getSum() {
グラフいいね✨

2022-09-26 10:06 UTC, risako070310 commented on app/src/main/java/app/nakaura/chloe/original/todo/ToDoFragment.kt
> +        val apple:Float = appleArraySum.toFloat()
細かいけど！:の後に空白を入れよう〜

```suggestion
        val apple: Float = appleArraySum.toFloat()
```

2022-09-27 09:14 UTC, risako070310 reviewed
@Yu-Nakaura 
ログインのところ、やはり端末依存でうまく表示されない場合がありそう、、！
[この記事](https://qiita.com/naoi/items/5149e5e46a99f1295287)とかを参考にbiasで調整してみるといいかも？わからなかったらまた質問してください〜

2022-09-27 09:14 UTC, risako070310 commented on app/src/main/java/app/nakaura/chloe/original/todo/ToDoFragment.kt
> +        val apple: Float = appleArraySum.toFloat()
👍

2022-09-27 09:14 UTC, risako070310 commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_marginTop="23dp"
パスワードのところが表示されなくなっちゃったかも、、？？

<img src="https://user-images.githubusercontent.com/47821463/192485423-2435306c-7f7f-43c3-8957-57bff36bc0be.png" width=300>

2022-09-27 09:28 UTC, risako070310 approved these changes
LGTM！！！🥳

2022-09-27 09:30 UTC, Yu-Nakaura commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_marginTop="23dp"
![スクリーンショット (19)](https://user-images.githubusercontent.com/112265560/192489563-e89bf855-a2ca-46e1-af3e-4894a94d001b.png)
pixel 3 emulatorのスクショです！

2022-09-27 09:31 UTC, merged

2022-09-27 09:31 UTC, risako070310 commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_marginTop="23dp"
ナイスう！！！！